export const seoData = {
  titles: [
    "WebTech Studio - Best Web Development Company in Agra, India",
    "Web Tech Studio | Professional Website Design & SEO Services",
    "Top Web Development Agency | WebTech Studio",
    "Expert Web Development & Branding | Web Tech Studio",
    "Best Website Development Services - Web Tech Studio",
    "Custom Web Development & UI/UX Design | WebTech Studio",
    "SEO & Website Development Experts | Web Tech Studio",
    "High-Performance Websites & Digital Branding | WebTech Studio",
    "WebTech Studio - Affordable Web Design & SEO Services",
    "E-Commerce & Business Website Development | Web Tech Studio",
    "WebTech Studio - Leading Digital Marketing & Web Solutions",
    "Premium Website Design & SEO - Web Tech Studio",
    "Boost Your Business with WebTech Studio's Web Solutions",
    "WebTech Studio - Cutting-Edge Web Development & SEO",
    "Next-Gen Web & Branding Solutions | Web Tech Studio",
    "Top-Rated Website Development & SEO | WebTech Studio",
    "WebTech Studio - Transforming Businesses Online",
    "Scalable Web Solutions for Enterprises | Web Tech Studio",
    "WebTech Studio - AI-Driven Web Development & SEO",
    "Tailored Digital Strategies for High-Ticket Clients | WebTech Studio",
  ],
  descriptions: [
    "WebTech Studio is a leading web development agency specializing in custom website design, SEO, UI/UX, and digital branding.",
    "Build your dream website with Web Tech Studio. We provide expert web development, SEO services, and UI/UX design solutions.",
    "Want a powerful online presence? WebTech Studio offers top-tier website development, SEO, and branding services to boost your business.",
    "WebTech Studio helps businesses grow with modern, responsive websites, SEO strategies, and creative digital solutions.",
    "Get the best web development and SEO services with Web Tech Studio. We help businesses achieve online success.",
    "Rank higher and attract more customers with WebTech Studio's expert website design, branding, and digital marketing services.",
    "WebTech Studio specializes in building high-performance websites that convert. Get a competitive edge in your industry.",
    "Create a stunning online presence with Web Tech Studio. Professional web development, SEO, and UI/UX services tailored for you.",
    "Need a modern and effective website? WebTech Studio offers industry-leading web development and SEO strategies.",
    "From custom websites to SEO, Web Tech Studio helps businesses dominate search results and attract more clients.",
    "Take your brand to the next level with WebTech Studio's cutting-edge web solutions.",
    "Boost your website ranking and attract more clients with Web Tech Studio's expert SEO and design services.",
    "WebTech Studio is your trusted partner for website design, branding, and online growth.",
    "Drive business success with WebTech Studio's innovative digital marketing and SEO strategies.",
    "WebTech Studio - Your gateway to digital excellence and high-performance web solutions.",
    "Maximize conversions with WebTech Studio’s data-driven SEO and web development services.",
    "High-ticket web solutions for businesses aiming for exponential growth.",
    "WebTech Studio helps brands scale with enterprise-level website solutions.",
    "Tailored SEO and branding services for high-value clients and premium markets.",
    "Dominate your niche with WebTech Studio’s expert SEO and web development strategies.",
  ],
  keywords: [
    "web development agency",
    "website design company",
    "SEO services",
    "branding agency",
    "UI/UX design",
    "custom web development",
    "e-commerce website development",
    "best web development company",
    "website development services",
    "affordable website design",
    "responsive website design",
    "SEO for small businesses",
    "local SEO services",
    "top-rated web agency",
    "digital marketing services",
    "business website development",
    "corporate website solutions",
    "mobile-friendly web design",
    "high-performance website development",
    "SEO-friendly web design",
    "fast-loading website design",
    "CMS website development",
    "WordPress development services",
    "e-commerce SEO",
    "online branding solutions",
    "professional web solutions",
    "modern website design",
    "conversion-focused web design",
    "creative web agency",
    "website optimization services",
    "WebTech Studio SEO services",
    "WebTech Studio website development",
    "best web development agency in India",
    "website redesign services",
    "custom landing page design",
    "website speed optimization",
    "mobile-first web design",
    "high-ranking website strategies",
    "advanced SEO tactics",
    "search engine optimization",
    "growth hacking strategies",
    "digital transformation services",
    "full-stack web development",
    "online reputation management",
    "ecommerce store optimization",
    "Google ranking improvement",
    "social media marketing services",
    "content marketing strategies",
    "AI-powered website development",
    "SEO strategies for high-ticket clients",
    "luxury brand website solutions",
    "premium website development services",
    "exclusive SEO solutions for high-end businesses",
    "top-tier web design services",
    "WebTech Studio enterprise solutions",
    "scalable digital growth solutions",
    "tailored SEO for premium markets",
    "high-ticket website development",
    "digital branding for high-value clients",
  ],
};
